### ISSUE TITLE
Updated icon

### ISSUE THREAD

**Issue by armand-leguillou** [gentlecat/counter#107]
**Hello!**
I refresh the icon/logo of the app! It wasn't working with the themed icon and it looked a little old.
I did it with Illustrator so I can send you the .ai file (not supported here unfortunately). I also used the Roboto font because it's the default font on Android.
Send me feedback!
(english is not my first language (I may have made mistakes)

![Counter-Icon](https://github.com/gentlecat/counter/assets/78372784/af599b3f-09c8-4615-a613-7d2e8b584993)
![Counter-Icon-Themed](https://github.com/gentlecat/counter/assets/78372784/be5e8189-96c7-4ec6-8889-26a2265ba20a)

**Comment by gentlecat** [comment]
Hi, thanks a lot! Are you able to upload it elsewhere? Also, there are some guidelines which Google shares here:

* https://developer.android.com/distribute/google-play/resources/icon-design-specifications
* https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

I have something like this in mind:

![icon](https://github.com/gentlecat/counter/assets/460525/f4c5d8e6-aa18-4c64-b6d6-845f1943752c)

Not sure how well that'll work with adaptive design, but should be a bit more in line with their spec.

**Comment by armand-leguillou** [comment]
hi!
thank to your feedback!!
I will try your idea as soon as possible. does the 42 has a specific signification for you?

**Comment by gentlecat** [comment]
Yeah, that looks great! Are you able to share these in the original format so that I can add them?

**Comment by armand-leguillou** [comment]
thanks!!
yes here are the files: https://fromsmash.com/Counter-Icon
i remain at your disposal if you have any other comments!

have a good day!

**Comment by gentlecat** [comment]
Attaching here as well: [Counter-Icon.zip](https://github.com/gentlecat/counter/files/12534782/Counter-Icon.zip)

**Comment by gentlecat** [comment]
Had to make some slight adjustments, but I think it looks alright.

<img width="310" alt="Screenshot 2023-09-06 at 18 30 29" src="https://github.com/gentlecat/counter/assets/460525/74205fc2-7538-4279-941d-1d8c661fb962">

<img width="331" alt="Screenshot 2023-09-06 at 18 28 26" src="https://github.com/gentlecat/counter/assets/460525/35792ebc-e9bb-4909-b137-9dce107b4234">

I'll add that to the next version.

**Comment by gentlecat** [comment]
I published an update to Play Store and it should be released with the new icon pretty soon. Thanks again for prompting this. I think it looks way better now!

**Comment by armand-leguillou** [comment]
yeah I had the update!!
thanks, amazing work 🙌🏼
