### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by avillafiorita** [gentlecat/counter#34]
a timestamp could be associated to each counter.
a log of <timestamps, counter> could also keep track of the history of updates

two possible usages:
1. you always know when you last updated any given counter ("did I count the coffee I took at lunch?")
2. you get the pattern of your behaviours ("how many coffees do I drink per day?")

in any case, great app also as it is!

**Comment by wandersonwhcr** [comment]
+1

**Comment by Qu4tro** [comment]
+1

**Comment by funnyflowerpot** [comment]
Together with #4 this would be really handy.
After some long search I couldn't find an app on F-Droid that would allow me to track how often I have done something each day. With timestamps and file export this app would fill the niche really well!
Apart from that, great app!

**Comment by vramazani** [comment]
For an open source (GPL3) app having this functionality, see: (although Counter is simpler in UI)
Track & Graph
https://f-droid.org/app/com.samco.trackandgraph
https://github.com/SamAmco/track-and-graph

Maybe use their code? (assuming the license grants this)

**Comment by funnyflowerpot** [comment]
Thanks @vramazani for the reference!

Good idea to look at the license. The [Track & Graph license](https://github.com/SamAmco/track-and-graph/blob/master/LICENSE.txt) is GPL3, while [this project](https://github.com/gentlecat/counter/blob/master/LICENSE.txt) uses the Apache License 2.0. According to the [Apache Software Foundation](https://www.apache.org/licenses/GPL-compatibility.html), it seems code from Track & Graph cannot be included, unfortunately:

> Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, **GPLv3 software cannot be included in Apache projects**. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.
>
> This licensing incompatibility applies _only_ when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.

(Bold emphasis added, italic in original.)
