### ISSUE TITLE
Add Animation and different color themes

### ISSUE THREAD

**Issue by Saiprashanth-1993** [gentlecat/counter#42]
Thank you. Very useful app :)

Please add animation for each counts and apart from dark and light add Multiple color schemes..

**Comment by gentlecat** [comment]
Thanks for your feedback! The app already had a dark color scheme (you can switch to it in the settings). Regarding animations, I'm not quite sure what you mean. If you can describe what you have in mind perhaps someone could implement that.

I'll close this for now.
