### ISSUE TITLE
Show values of counters in the list

### ISSUE THREAD

**Issue by gentlecat** [gentlecat/counter#66]
*Significant number of people are requesting this feature. Seems like something that would be nice to have.*

**Comment by Charpy** [comment]
+1 for the current counter value in the list, but also at the bottom a "sum of all counters" value would be great !
Thx for this valuable app !

**Comment by dougrk** [comment]
I like Charpy's suggestion for showing a sum, but I haven't committed anything yet due to some ugly layout behavior when I tried to add one. I may include it if I find a way to improve it.

**Comment by gentlecat** [comment]
I don't think we need to add a sum at that point.

**Comment by dougrk** [comment]
To follow up and clarify, the 4 commits in PR #69 are all good, they do not contain any experimental code for displaying a sum. The numbers in the list look good visually and I verified that they update in all possible situations where the counter is changed. Please take a look!

**Comment by gentlecat** [comment]
Thank you. I'll try to take a look soon.

**Comment by Charpy** [comment]
Awesome ! 

Le 1 mars 2019 21:07:33 GMT+01:00, Roman Tsukanov <notifications@github.com> a écrit :
>Thank you. I'll try to take a look soon.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gentlecat/counter/issues/66#issuecomment-468795168

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
