### ISSUE TITLE
I don't understand CounterApplication Class

### ISSUE THREAD

**Issue by xee95** [gentlecat/counter#81]
`   
      public class CounterApplication extends Application {
       public static String PACKAGE_NAME;

    @Inject DispatchingAndroidInjector<Activity> dispatchingAndroidInjector;

    private static CounterApplicationComponent component;

    @Override
    public void onCreate() {
      super.onCreate();

      component =
          DaggerCounterApplicationComponent.builder().counterModule(new 
    CounterModule(this)).build();

    PACKAGE_NAME = getApplicationContext().getPackageName();
    }

    public static CounterApplicationComponent getComponent() {
    return component;
    }
     }`

i don't understand this class, in my project this class is not working any help

**Comment by gentlecat** [comment]
Take a look at https://developer.android.com/reference/android/app/Application?hl=en.
