### ISSUE TITLE
Feature: add button to aggregate

### ISSUE THREAD

**Issue by vramazani** [gentlecat/counter#82]
Creating a unidirectional link between two counters, one would get a button to add its value to the other's existing value, and resetting itself.

**Comment by gentlecat** [comment]
I think that's a bit out of scope. Sorry.

**Comment by vramazani** [comment]
for anyone looking for such an app:
Track & Graph
https://f-droid.org/app/com.samco.trackandgraph
https://github.com/SamAmco/track-and-graph
