### ISSUE TITLE
How to install recent version (21 or 22)?

### ISSUE THREAD

**Issue by Flnch** [gentlecat/counter#92]
I installed the most recent version from Google Play and in the app settings it states this is version 20. Installing from F-Droid also yields version 20.

However, the [releases](https://github.com/gentlecat/counter/releases) on GitHub show there exist two more recent versions 21 and 22. Release 22 is also shown differently on the GitHub releases page. Is there something broken or do I simply need to wait until the more recent version is published to the app stores?

**Comment by gentlecat** [comment]
Latest version hasn't been deployed in Google Play at the time (it should be available now).

As for F-Droid, it looks like [package metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/me.tsukanov.counter.yml) is outdated. I'll try to submit an update to them.

**Comment by gentlecat** [comment]
Here's the update: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7014

**Comment by Flnch** [comment]
Nice, in Google Play it is now available. Thanks! F-Droid will need some time until they merge I think.
